spring:
  application:
    name: PackUp-Backend

  security:
    user:
      name: admin
      password: 1234
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: "naver_client_id"
            client-secret: "naver_client_secret"
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
          google:
            client-name: google
            client-id: "google_client_id"
            client-secret: "google_client_secret"
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: name, email
          kakao:
            client-name: kakao
            client-id: "kakao_client_id"
            client-secret: "kakao_client_secret"
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    static-path-pattern: /static/**

  web:
    resources:
      static-locations:
        - classpath:/static/

  # 데이터소스 설정
  datasource:
    url: jdbc:log4jdbc:mysql://3.35.147.68:3306/SWYP6?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: swyp6
    password: Swyp10_6group
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 300
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
   redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: 0219songhongseob@gmail.com
    password: wwrugfhcaenqtptn
    properties:
      mail:
       smtp:
        auth: true
        starttls:
         enable: true
         required: true
      debug: true

  # jwt 설정
  jwt:
    secret: thisIsASecretKeyWithAtLeast32ByteLength123!!


  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, validate, update, none
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:logback-spring.xml

server:
  port: 8080
  tomcat:
   max-part-count: -1

file:
  upload:
    path: C:/temp/uploads/
    max-size: 52428800
    max-request-size: 104857600
    allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,txt

slack:
  client-id: slack_client_id
  client-secret: slack_client_secret
    
app:
  base-url: ${BASE_URL:http://localhost:8080}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}